#!/bin/sh

red='\033[0;31m';
gre='\033[0;32m';
yel='\033[0;33m';
ncl='\033[0m'; #No colour

echo "${gre}Post receive hook: Updating Ripple!${yel}"

export GIT_WORK_TREE=/ripple/master
cd $GIT_WORK_TREE
sudo -u deploy git pull
sudo -u deploy git checkout master -f

echo "${gre}Deploy: Re-linking scripts directory.${ncl}"
sudo -u deploy rm -f /home/deploy/scripts
sudo -u deploy ln -s /ripple/master/Server/home/deploy/scripts /home/deploy/scripts
echo "${gre}Scripts relinked.${ncl}";

echo "${gre}Deploy: Re-linking templates directory.${ncl}"
sudo -u deploy rm -f /home/deploy/templates
sudo -u deploy ln -s /ripple/master/Server/home/deploy/templates /home/deploy/templates
echo "${gre}Templates relinked.${ncl}";

echo "${gre}Git: Re-linking scripts directory.${ncl}"
rm /home/git/scripts
ln -s /ripple/master/Server/home/git/scripts /home/git/scripts
echo "${gre}Scripts relinked.${ncl}";

echo "${gre}Git: Re-linking templates directory.${ncl}"
rm -f /home/git/templates
ln -s /ripple/master/Server/home/git/templates /home/git/templates
echo "${gre}Templates relinked.${ncl}";

echo "${gre}Bot: Re-linking trigger.${ncl}"
sudo -u bot rm -f /home/bot/trigger.sh
sudo -u bot ln -s /ripple/master/Server/home/bot/trigger.sh /home/bot/trigger.sh
echo "${gre}Trigger relinked.${ncl}";

echo "${gre}Done!${ncl}"