#!/bin/sh

red='\033[0;31m';
gre='\033[0;32m';
yel='\033[0;33m';
pur="\033[0;35m";
cya="\033[0;36m";
ncl='\033[0m'; #No colour

echo "${gre}Post receive hook: Updating Ripple!${ncl}"

export GIT_WORK_TREE=/ripple/master
cd $GIT_WORK_TREE
sudo -u deploy git pull
sudo -u deploy git checkout master -f

echo "${pur}[Deploy] Re-linking scripts directory.${ncl}"
sudo -u deploy rm -f /home/deploy/scripts
sudo -u deploy ln -s /ripple/master/Server/home/deploy/scripts /home/deploy/scripts
echo "${cya}         Scripts relinked.${ncl}";

echo "${pur}[Deploy] Re-linking templates directory.${ncl}"
sudo -u deploy rm -f /home/deploy/templates
sudo -u deploy ln -s /ripple/master/Server/home/deploy/templates /home/deploy/templates
echo "${cya}         Templates relinked.${ncl}";

echo "${pur}[ Git  ] Re-linking scripts directory.${ncl}"
rm -f /home/git/scripts
ln -s /ripple/master/Server/home/git/scripts /home/git/scripts
echo "${cya}         Scripts relinked.${ncl}";

echo "${pur}[ Git  ] Re-linking templates directory.${ncl}"
rm -f /home/git/templates
ln -s /ripple/master/Server/home/git/templates /home/git/templates
echo "${cya}         Templates relinked.${ncl}";

echo "${pur}[ Bot  ] Re-linking trigger.${ncl}"
sudo -u bot rm -f /home/bot/trigger.sh
sudo -u bot ln -s /ripple/master/Server/home/bot/trigger.sh /home/bot/trigger.sh
echo "${cya}         Trigger relinked.${ncl}";

echo "${gre}Done!${ncl}"